### PR TITLE
Formatting of python code fencing for SidecarEvaluatorModelExport

### PR DESCRIPTION
**Pull request by SuryanarayanaY**
In the tensorflow.org the documentation page of tf.keras.callbacks.SidecarEvaluatorModelExport showing content of raw HTML pages. The reason may be that the Python code fence was not closed causing the page view breaking. Hence correcting the mistake.

May Fixes TF ticket [#61375](https://github.com/tensorflow/tensorflow/issues/61375)

### CODE REVIEW

**Review by grasskin — CHANGES_REQUESTED** [review]
Thank you for finding this, please add a new line after the ```. Thank you!

**Comment by SuryanarayanaY** [comment]
Done the changes requested. Thank you!

**Review by grasskin — APPROVED** [review]
LGTM, thank you!

**Comment by grasskin** [comment]
Looks like it's failing lint check, please run sh shell/lint.sh and remove the whitespace from the newline.

**Comment by gbaned** [comment]
Hi @SuryanarayanaY Can you please check @grasskin's [comments](https://github.com/keras-team/tf-keras/pull/657#issuecomment-1741289830) ? Thank you!

**Comment by gbaned** [comment]
Hi @SuryanarayanaY Any update on this PR? Please. Thank you!

**Comment by SuryanarayanaY** [comment]
Opened a new PR#723.

**Pull request closed without merging**
